/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c314c07b6be73244126e36ed962b2404)
interface __BaseEnv_Env {
	DB: D1Database;
	AI_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	OPENAI_NEXT_MODEL: "gpt-5.4-mini";
	OPENAI_NEXT_API_KEY: string;
	OPENAI_NEXT_BASE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_NEXT_MODEL" | "OPENAI_NEXT_API_KEY" | "OPENAI_NEXT_BASE_URL">> {}
}
